services:
  mongodb:
    image: 'mongo:8.0.4'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_DATABASE=workflow-management'
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
